apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: simple-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  type: NodePort
  selector:
    app: simple-app
  ports:
    - port: 80
      targetPort: 80